{% set version = '0.3-3' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-pbdzmq
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/pbdZMQ_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/pbdZMQ/pbdZMQ_{{ version }}.tar.gz
  sha256: ae26c13400e2acfb6463ff9b67156847a22ec79f3b53baf65119efaba1636eca

build:
  merge_build_host: True  # [win]
  number: 1001
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}sed               # [win]
    - {{posix}}grep              # [win]
    - {{posix}}autoconf
    - {{posix}}automake          # [not win]
    - {{posix}}automake-wrapper  # [win]
    - {{posix}}pkg-config
    - {{posix}}make
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - zeromq                     # [not win]
    - {{native}}zeromq 4.1.*     # [win]
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - zeromq                     # [not win]
    - {{native}}zeromq 4.1.*     # [win]

test:
  commands:
    - $R -e "library('pbdZMQ')"           # [not win]
    - "\"%R%\" -e \"library('pbdZMQ')\""  # [win]

about:
  home: http://r-pbd.org/
  license: GPL-3
  summary: "'ZeroMQ' is a well-known library for high-performance asynchronous messaging in
    scalable, distributed applications.  This package provides high level R wrapper
    functions to easily utilize 'ZeroMQ'. We mainly focus on interactive client/server
    programming frameworks. For convenience, a minimal 'ZeroMQ' library (4.2.2) is
    shipped with 'pbdZMQ', which can be used if no system installation of 'ZeroMQ'
    is available.  A few wrapper functions compatible with 'rzmq' are also provided."
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - ocefpaf
    - mingwandroid
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
